# Generated by Django 3.0.5 on 2024-05-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20240503_0250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='id',
        ),
        migrations.AlterField(
            model_name='userbook',
            name='book_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
